part_2/core/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
]

part_2/core/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

part_2/core/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>', views.category_list, name='category_list'),
]

part_2/core/basket/models.py
from django.db import models

# Create your models here.

part_2/core/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.query import QuerySet
from django.urls import reverse


# Creating modelManager() to readily filter is_active=True
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Category(models.Model):
    name = models.CharField(max_length=25, db_index=True)
    slug = models.SlugField(max_length=25, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='product_creator', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default_image.png')
    slug = models.SlugField(max_length=25, unique=True)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # using ProductManager()
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

part_2/core/basket/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse

from .basket import Basket
from store.models import Product

def basket_summary(request):

    return render(request, 'store/basket/summary.html')


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productId'))
        product_qty = int(request.POST.get('productQty'))
        # print(product_qty)
        product = get_object_or_404(Product, id=product_id)
        
        # basket.add(product=product, product_qty=product_qty)
        basket.add(product=product, product_qty=product_qty)
        basket_qty = basket.__len__()
        # print(basket_qty)
        response = JsonResponse({
            'quantity': basket_qty
        })
        return response

part_2/core/store/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product


def product_all(request):
    
    # products = Product.objects.filter(is_active=True)
    # using a modelManagr() instead of filtering
    products = Product.products.all()
    context = {
        'products': products
    }
    return render(request, 'store/home.html', context)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/single.html', {'product':product})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    context = {
        'category': category,
        'products': products
    }
    return render(request, 'store/products/category.html', context)

part_2/core/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css"
        integrity="sha512-ZnR2wlLbSbr8/c9AgLg3jQPAattCUImNsae6NHYnS9KrIwRdcY9DxFotXhNAKIKbAXlRnujIqUWoXXwqyFOeIQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- <script src="https://code.jquery.com/jquery-3.7.0.min.js"
        integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script> -->
    <script src="{% static 'js/jquery_nv.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <title>{% block title %} My Shop {% endblock %}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'store:product_all' %}">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'store:product_all' %}">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Library
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">All</a></li>
                                {% for c in categories %}
                                <li>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}

                            </ul>
                        </li>
                    </ul>
                    <a href="{% url 'basket:basket_summary' %}" role="button" type="button" class="btn btn-secondary">

                        {% with total_qty=basket|length  %}
                        {% if total_qty > 0 %}
                        <div id="basket-qty" class="d-inline-flex">{{ total_qty }}</div>
                        {% else %}
                        <div id="basket-qty" class="d-inline-flex">0</div>
                        {% endif %}

                        {% endwith %}

                        <i class="bi bi-basket"></i>
                        Basket
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div id="content">
        {% block content %}

        {% endblock content %}
    </div>
</body>

</html>

part_2/core/templates/store/basket/summary.html
{% extends "../base.html" %}

{% load static %}

{% block title %} Basket Summary {% endblock title %}

{% block content %}
<h1>Basket page</h1>
{% endblock content %}

part_2/core/templates/store/home.html
{% extends "./base.html" %}
{% load static %}

{% block title %}
BookStore
{% endblock title %}

{% block content %}
<section class="container py-5 text-center">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="h1 fw-bold">Search, Read, Buy, Review</h1>
            <p class="lead text-muted">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi corrupti excepturi voluptates nobis
                quibusdam exercitationem.
            </p>
            <p>
                <a href="" class="btn btn-primary my-2">Create an account</a>
            </p>
        </div>
    </div>
</section>

<div class="container">
    <div class="pb-3 h3">All Books</div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products  %}
        <div class="card" style="width: 18rem;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">
                    <a href="{{ product.get_absolute_url }}" class="text-dark text-decoration-none">
                        {{ product.title }}
                    </a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9mins read</small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

part_2/core/templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}

{% block title %}
{% if category %}
{{ category.name }}
{% else %}
<h3>Products</h3>
{% endif %}

{% endblock title %}

{% block content %}

<div class="container">
    <div class="pb-3 h3">{{ category|title }} Books</div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products  %}
        <div class="card" style="width: 18rem;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">
                    <a href="{{ product.get_absolute_url }}" class="text-dark text-decoration-none">
                        {{ product.title }}
                    </a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9mins read</small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

part_2/core/templates/store/products/single.html
{% extends "../base.html" %}

{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img src="{{ product.image.url }}" class="img-fluid mx-auto d-block" width="200px" alt="">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span>(Author)</p>
                <p>{{ product.description|slice:"355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">{{ product.price }} CFA</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select name="" id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>
                            </div>
                            <div class="col-6 text-end">
                                <button id="add-button" value="{{product.id}}" type="button"
                                    class="btn btn-primary btn-sm">Add to
                                    Basket</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        // console.log(e)
        // console.log($('#select option:selected').text())

        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productId: $('#add-button').val(),
                // productQty: $('#select').val(),
                productQty: $('#select option:selected').text(),
                csrfmiddlewaretoken: '{{csrf_token}}',
                action: 'post'
            },
            success: function (json) {
                console.log(json)
                document.getElementById('basket-qty').innerHTML = json.quantity
                // console.log(bas)
            },
            error: function (xhr, errmsg, err) {

            }
        });
    })
</script>
{% endblock content %}