part_1/core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

part_1/core/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('item/<slug:slug>', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>', views.category_list, name='category_list'),
]

part_1/core/store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=25, db_index=True)
    slug = models.SlugField(max_length=25, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='product_creator', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=25, unique=True)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

part_1/core/store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def categories(request):
    return {
        'categories': Category.objects.all()
    }


def all_products(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'store/home.html', context)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/detail.html', {'product': product})


def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    context = {
        'category': category,
        'products': products
    }
    return render(request, 'store/products/category.html', context)

part_1/core/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <title>{% block title %} My Shop {% endblock %}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'store:all_products' %}">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                                href="{% url 'store:all_products' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Library
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">All</a></li>
                                {% for c in categories %}
                                <li>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}

                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled">Disabled</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div id="content">
        {% block content %}

        {% endblock content %}
    </div>
</body>

</html>

part_1/core/templates/store/home.html
{% extends "./base.html" %}
{% load static %}

{% block title %}
Home
{% endblock title %}

{% block content %}
<section class="container py-5 text-center">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="h1 fw-bold">Search, Read, Buy, Review</h1>
            <p class="lead text-muted">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi corrupti excepturi voluptates nobis
                quibusdam exercitationem.
            </p>
            <p>
                <a href="" class="btn btn-primary my-2">Create an account</a>
            </p>
        </div>
    </div>
</section>

<div class="container">
    <div class="pb-3 h3">All Books</div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products  %}
        <div class="card" style="width: 18rem;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">
                    <a href="{{ product.get_absolute_url }}" class="text-dark text-decoration-none">
                        {{ product.title }}
                    </a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9mins read</small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

part_1/core/templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}

{% block title %}
Home
{% endblock title %}

{% block content %}

<div class="container">
    <div class="pb-3 h3">{{ category|title }} Books</div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products  %}
        <div class="card" style="width: 18rem;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">
                    <a href="{{ product.get_absolute_url }}" class="text-dark text-decoration-none">
                        {{ product.title }}
                    </a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9mins read</small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

part_1/core/templates/store/products/detail.html
{% extends "../base.html" %}

{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img src="{{ product.image.url }}" class="img-fluid mx-auto d-block" width="200px" alt="">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span>(Author)</p>
                <p>{{ product.description|slice:"355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">{{ product.price }} CFA</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select name="" id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>
                            </div>
                            <div class="col-6 text-end">
                                <button type="button" class="btn btn-primary">Add to Basket</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock content %}